base_url = "https://aleksandergondek.github.io"

title = "aleksandergondek.github.io"
description = "Description of my blog, to be filled in"

theme = "adidoks"

default_language = "en"
output_dir = "public"

generate_feed = true
author = "Aleksander Gondek"

taxonomies = [
  {name = "authors"}, # Basic definition: no feed or pagination
  {name = "tags", feed = true}, # each tag will have its own feed
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
highlight_code = true
# highlight_theme = "monokai" # todo: Isn't the default better?
render_emoji = false

[extra]
author = "Aleksander Gondek"
github = "https://github.com/AleksanderGondek"
twitter = ""
email = "gondekaleksander@protonmail.com"

# If running on netlify.app site, set to true
is_netlify = false

# Set HTML file language
language_code = "en-GB"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "Title addition to be filled in."

# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "Europe/Warsaw"

# Edit page on reposity or not
edit_page = false
docs_repo = "https://github.com/AleksanderGondek/gondekaleksander.github.io"
repo_branch = "main"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

## Open Graph + Twitter Cards
[extra.open]
enable = true
# this image will be used as fallback if a page has no image of its own
image = "doks.png"
twitter_site = ""
twitter_creator = "AleksanderGondek"
facebook_author = "AleksanderGondek"
facebook_publisher = "AleksanderGondek"
og_locale = "en_GB"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-doks.png"
linked_in = "https://www.linkedin.com/in/AleksanderGondek"
github = "https://github.com/AleksanderGondek"
section = "blog" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false

# Menu items
[[extra.menu.main]]
name = "Blog"
section = "blog"
url = "/blog/"
weight = 10

[[extra.menu.main]]
name = "Freelance"
section = "freelance"
url = "/hire-me/"
weight = 20

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/AleksanderGondek"
post = "v0.1.0"
weight = 20

# Footer contents
[extra.footer]
info = 'Powered by <a href="https://www.getzola.org/">Zola</a>'
