version: 2
jobs:
  lint_and_build:
    docker:
      - image: circleci/node:8-stretch-browsers
    working_directory: ~/blog
    steps:
      - checkout
      - run:
          name: Install node dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Build
          command: yarn run build
  deploy:
    docker:
      - image: circleci/node:8-stretch-browsers
    working_directory: ~/blog
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:43:4a:3b:ff:e0:f8:87:81:30:58:5d:4b:8f:4b:dd"
      - run: 
          name: "Configure git defaults"
          command: |
            git config --global user.email "gondekaleksander@hotmail.com"
            git config --global user.name "Aleksander Gondek"
      - checkout
      - run:
          name: Install node dependencies
          command: yarn
      - run:
          name: Deploy
          command: yarn run deploy
workflows:
  version: 2
  main_flow:
    jobs:
      - lint_and_build
      - deploy:
          requires:
            - lint_and_build
